import { StringOrRegExp } from '@cucumber/cucumber-expressions'

import { Language, TreeSitterSyntaxNode } from './types.js'

export const pythonLanguage: Language = {
  toParameterTypeName(node: TreeSitterSyntaxNode) {
    switch (node.type) {
      case 'string': {
        return stringLiteral(node)
      }
      case 'concatenated_string': {
        return stringLiteral(node)
      }
      case 'identifier': {
        return node.text
      }
      default: {
        throw new Error(`Unsupported node type ${node.type}`)
      }
    }
  },
  toParameterTypeRegExps(node: TreeSitterSyntaxNode) {
    switch (node.type) {
      case 'string': {
        return RegExp(cleanRegExp(stringLiteral(node)))
      }
      case 'concatenated_string': {
        return RegExp(cleanRegExp(stringLiteral(node)))
      }
      case 'identifier': {
        return RegExp(cleanRegExp(stringLiteral(node)))
      }
      default: {
        throw new Error(`Unsupported node type ${node.type}`)
      }
    }
  },
  toStepDefinitionExpression(node: TreeSitterSyntaxNode): StringOrRegExp {
    // This removes the head and tail apostrophes.
    // TODO: This should be temporary. Python supports
    // a wider array of regex features than javascript
    // a singular way of communicating regex consistent
    // across languages is necessary
    return toStringOrRegExp(node.text)
  },
  defineParameterTypeQueries: [
    `(call
      arguments: (argument_list
        (keyword_argument
          name: (identifier) @name-key
          value: (string) @name
          (#eq? @name-key "name")
        )?
        (keyword_argument
          name: (identifier) @regexp-key
          value: (string) @expression
          (#eq? @regexp-key "regexp")
        )?
        (keyword_argument
          name: (identifier) @regexp-key
          value: (concatenated_string) @expression
          (#eq? @regexp-key "regexp")
        )?
     ))@root`,
  ],
  defineStepDefinitionQueries: [
    `
    (decorated_definition
      (decorator
        (call
          function: (identifier) @method
          arguments: (argument_list (string) @expression)
        )
      )
      (#match? @method "(given|when|then)")
    ) @root
`,
  ],
  snippetParameters: {
    int: { type: 'int' },
    float: { type: 'float' },
    word: { type: 'str' },
    string: { type: 'str' },
    double: { type: 'double' },
    bigdecimal: { type: 'decimal' },
    byte: { type: 'byte' },
    short: { type: 'short' },
    long: { type: 'long' },
    biginteger: { type: 'int' },
    '': { type: 'Object', name: 'arg' },
  },
  defaultSnippetTemplate: `
  @{{ #lowercase }}{{ keyword }}{{ /lowercase }}('{{ expression }}')
  def step_{{ #lowercase }}{{ keyword }}{{ /lowercase }}(context, {{ #parameters }}{{ #seenParameter }}, {{ /seenParameter }}{{ name }}{{ /parameters }}) :
      # This was autogenerated using cucumber syntax.
      # Please convert to use regular expressions, as Behave does not currently support Cucumber Expressions`,
}

function cleanRegExp(regExpString: string): string {
  const startsWith = regExpString[0]
  switch (startsWith) {
    case '/':
      return regExpString.slice(1, -1)
    default:
      return regExpString
  }
}
export function toStringOrRegExp(step: string): StringOrRegExp {
  return isRegExp(step.slice(1, -1))
    ? RegExp(cleanRegExp(step.slice(1, -1).split('?P').join('')))
    : step.slice(1, -1)
}

function stringLiteral(node: TreeSitterSyntaxNode): string {
  const isFString = node.text.startsWith('f')
  const cleanWord = isFString ? node.text.slice(1).slice(1, -1) : node.text.slice(1, -1)
  const postSplitCleanWord = cleanWord
    .split('\\\n')
    .join('')
    .split('|')
    .map((x) => x.replace(/\"/g, ''))
    .map((x) => x.trim())
    .join('|')
  return postSplitCleanWord
}

export function isRegExp(cleanWord: string): boolean {
  const startsWithSlash = cleanWord.startsWith('/')
  const namedGroupMatch = /\?P/
  const specialCharsMatch = /\(|\)|\.|\*|\\|\|/
  const containsNamedGroups = namedGroupMatch.test(cleanWord)
  const containsSpecialChars = specialCharsMatch.test(cleanWord)
  return startsWithSlash || containsNamedGroups || containsSpecialChars
}
