name: Release NPM

permissions: {}

on:
  push:
    branches: [release/*]

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          # See https://github.com/tree-sitter/tree-sitter/blob/v0.24.6/cli/loader/emscripten-version
          # (choose the Git tag that corresponds to the version of web-tree-sitter specified in package.json)
          # Should be kept in sync with .github/workflows/test-javascript.yml
          version: 3.1.64
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: npm install-ci-test
      - run: npm publish
